version: "3.8"

services:
  api:
    build: .
    container_name: ecommerce_api
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      DATABASE_URL: postgres://user:pass@db:5432/ecommerce?sslmode=disable
      JWT_SECRET: supersecretkey
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
